-- Platform audit trail. One append-only row per audited action. The details map is stored as a JSON
-- document in a large-object column so arbitrary structured context survives without a fixed schema.
-- H2-tested; on PostgreSQL the CLOB column maps to TEXT (decision D51).
CREATE TABLE IF NOT EXISTS platform_audit (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    action         VARCHAR(255) NOT NULL,
    actor          VARCHAR(255) NOT NULL,
    resource       VARCHAR(512),
    outcome        VARCHAR(16)  NOT NULL,
    occurred_at    TIMESTAMP    NOT NULL,
    correlation_id VARCHAR(64),
    details        CLOB,
    CONSTRAINT pk_platform_audit PRIMARY KEY (id)
);
