package ae.gov.dubaicustoms.platform.docs;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Stream;

/**
 * Emits {@code docs/reference/platform-index.json} — the machine-readable fact sheet the platform MCP
 * server serves to agents (phase-16 C.1). Everything is derived at build time from sources that are
 * already the single source of truth, so the index cannot rot:
 * <ul>
 *   <li>capabilities + starter coordinates + doc URL — from {@code platform-bom} and the
 *       {@code STARTER_TO_PAGE} map;</li>
 *   <li>config keys (+type/default/description/deprecation) — from aggregated
 *       {@code spring-configuration-metadata.json} via {@link PropertiesReferenceGenerator};</li>
 *   <li>error codes (+capability) — from {@code error-codes.csv};</li>
 *   <li>API/SPI type inventory (+@API status/since) — parsed from the api/spi module sources;</li>
 *   <li>usage snippets — fenced code blocks in the capability pages (tagged {@code snippet:<id>}
 *       when present, else keyed by capability).</li>
 * </ul>
 */
final class PlatformIndexGenerator {

    private static final ObjectMapper MAPPER = new ObjectMapper().enable(SerializationFeature.INDENT_OUTPUT);

    private PlatformIndexGenerator() {
    }

    /** Regenerates {@code docs/reference/platform-index.json}; returns the written path. */
    static Path generate() {
        ObjectNode root = MAPPER.createObjectNode();
        root.put("version", platformVersion());
        root.put("generatedNote", "Generated by PlatformIndexGenerator at build time. Do not edit by hand.");
        addCapabilities(root.putArray("capabilities"));
        addProperties(root.putArray("properties"));
        addErrorCodes(root.putArray("errorCodes"));
        addApiTypes(root.putArray("apiTypes"));
        addSnippets(root.putArray("snippets"));

        Path out = PlatformDocs.docsRoot().resolve("reference/platform-index.json");
        try {
            Files.createDirectories(out.getParent());
            MAPPER.writeValue(out.toFile(), root);
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
        return out;
    }

    /** The platform train version from the root reactor POM's {@code <revision>}. */
    static String platformVersion() {
        try {
            String rootPom = Files.readString(PlatformDocs.repoRoot().resolve("pom.xml"));
            Matcher m = Pattern.compile("<revision>([^<]+)</revision>").matcher(rootPom);
            return m.find() ? m.group(1).trim() : "unknown";
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    // --- capabilities + starters -------------------------------------------------------------

    private static void addCapabilities(ArrayNode out) {
        // One entry per capability page, listing every starter that maps to it and a one-line summary.
        Map<String, List<String>> startersByPage = new TreeMap<>();
        PlatformDocs.STARTER_TO_PAGE.forEach((starter, page) ->
                startersByPage.computeIfAbsent(page, p -> new ArrayList<>()).add(starter));

        startersByPage.forEach((page, starters) -> {
            String capability = capabilityOfPage(page);
            ObjectNode cap = out.addObject();
            cap.put("name", capability);
            cap.put("doc", page);
            cap.put("oneLiner", oneLiner(page));
            ArrayNode coords = cap.putArray("starters");
            starters.forEach(s -> coords.add("ae.gov.dubaicustoms.platform:" + s));
        });
    }

    private static String capabilityOfPage(String page) {
        // "modules/messaging.md" -> "messaging"; "testing.md" -> "testing".
        String file = page.substring(page.lastIndexOf('/') + 1);
        return file.endsWith(".md") ? file.substring(0, file.length() - 3) : file;
    }

    /** First prose paragraph of a capability page, flattened to one line. */
    private static String oneLiner(String page) {
        Path md = PlatformDocs.docsRoot().resolve(page);
        if (!Files.exists(md)) {
            return "";
        }
        try {
            for (String line : Files.readAllLines(md)) {
                String t = line.strip();
                if (t.isEmpty() || t.startsWith("#") || t.startsWith(">") || t.startsWith("|")
                        || t.startsWith("```") || t.startsWith("-") || t.startsWith("!")) {
                    continue;
                }
                return t.replaceAll("[*`\\[\\]]", "");
            }
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
        return "";
    }

    // --- properties --------------------------------------------------------------------------

    private static void addProperties(ArrayNode out) {
        for (PropertiesReferenceGenerator.Prop p : PropertiesReferenceGenerator.scan()) {
            ObjectNode node = out.addObject();
            node.put("name", p.name());
            node.put("type", p.type());
            node.put("default", p.defaultValue());
            node.put("description", p.description());
            node.put("deprecation", p.deprecation());
            node.put("capability", PlatformDocs.capabilityOfKey(p.name()));
        }
    }

    // --- error codes -------------------------------------------------------------------------

    private static void addErrorCodes(ArrayNode out) {
        Path csv = ErrorCodesReferenceGenerator.csvSource();
        if (!Files.exists(csv)) {
            return; // ErrorCodeRegistryTest has not run yet; a full `mvn verify` emits it
        }
        try {
            List<String> lines = Files.readAllLines(csv);
            lines.stream().skip(1).filter(l -> !l.isBlank()).forEach(line -> {
                int comma = line.indexOf(',');
                String code = comma < 0 ? line : line.substring(0, comma);
                String declaredBy = comma < 0 ? "" : line.substring(comma + 1);
                ObjectNode node = out.addObject();
                node.put("code", code);
                String[] parts = code.split("-");
                node.put("capability", parts.length >= 2 ? parts[1].toLowerCase() : "");
                node.put("declaredBy", declaredBy);
            });
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    // --- API/SPI type inventory --------------------------------------------------------------

    private static final Pattern PACKAGE = Pattern.compile("^package\\s+([\\w.]+)\\s*;", Pattern.MULTILINE);
    private static final Pattern API_STATUS =
            Pattern.compile("@API\\s*\\(\\s*status\\s*=\\s*(?:API\\.Status\\.)?(\\w+)"
                    + "(?:\\s*,\\s*since\\s*=\\s*\"([^\"]*)\")?");
    private static final Pattern TYPE_DECL =
            Pattern.compile("^public\\s+(?:final\\s+|abstract\\s+|sealed\\s+|non-sealed\\s+)*"
                    + "(class|interface|enum|record|@interface)\\s+(\\w+)", Pattern.MULTILINE);

    private static void addApiTypes(ArrayNode out) {
        Path root = PlatformDocs.repoRoot();
        Map<String, ObjectNode> byFqcn = new TreeMap<>();
        try (Stream<Path> tree = Files.walk(root)) {
            tree.filter(p -> p.toString().endsWith(".java"))
                    .filter(p -> {
                        String s = p.toString().replace('\\', '/');
                        return (s.contains("-api/src/main/java/") || s.contains("-spi/src/main/java/"))
                                && !s.contains("/internal/") && !s.endsWith("package-info.java");
                    })
                    .forEach(java -> readApiType(java, byFqcn));
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
        byFqcn.values().forEach(out::add);
    }

    private static void readApiType(Path java, Map<String, ObjectNode> byFqcn) {
        try {
            String src = Files.readString(java);
            Matcher pkg = PACKAGE.matcher(src);
            Matcher decl = TYPE_DECL.matcher(src);
            Matcher api = API_STATUS.matcher(src);
            if (!pkg.find() || !decl.find()) {
                return;
            }
            String fqcn = pkg.group(1) + "." + decl.group(2);
            ObjectNode node = MAPPER.createObjectNode();
            node.put("type", fqcn);
            node.put("kind", decl.group(1).equals("@interface") ? "annotation" : decl.group(1));
            node.put("status", api.find() ? api.group(1) : "");
            node.put("since", api.reset().find() && api.group(2) != null ? api.group(2) : "");
            byFqcn.put(fqcn, node);
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    // --- usage snippets ----------------------------------------------------------------------

    private static final Pattern FENCE =
            Pattern.compile("```([^\\n`]*)\\n(.*?)```", Pattern.DOTALL);

    private static void addSnippets(ArrayNode out) {
        // One snippet per capability page: an explicit `snippet:<id>` fenced block wins; otherwise the
        // page's first code block. Keyed by capability so usage_example(capability, task) can resolve.
        Map<String, String[]> byPage = new LinkedHashMap<>();
        PlatformDocs.STARTER_TO_PAGE.values().forEach(page -> byPage.putIfAbsent(page, null));
        byPage.keySet().forEach(page -> {
            String[] snippet = firstSnippet(page);
            if (snippet != null) {
                ObjectNode node = out.addObject();
                node.put("capability", capabilityOfPage(page));
                node.put("id", snippet[0]);
                node.put("code", snippet[1]);
            }
        });
    }

    /** Returns {@code [id, code]} for a page's tagged-or-first code block, or {@code null} if none. */
    private static String[] firstSnippet(String page) {
        Path md = PlatformDocs.docsRoot().resolve(page);
        if (!Files.exists(md)) {
            return null;
        }
        try {
            String content = Files.readString(md);
            Matcher m = FENCE.matcher(content);
            String capability = capabilityOfPage(page);
            String[] firstAny = null;
            while (m.find()) {
                String info = m.group(1).trim();
                String code = m.group(2).strip();
                String id = capability;
                int tag = info.indexOf("snippet:");
                if (tag >= 0) {
                    return new String[] {info.substring(tag + "snippet:".length()).trim(), code};
                }
                if (firstAny == null && !code.isBlank()) {
                    firstAny = new String[] {id, code};
                }
            }
            return firstAny;
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }
}
