package ae.gov.dubaicustoms.platform.docs;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Stream;

/**
 * Aggregates every module's build-time {@code spring-configuration-metadata.json} (which already
 * folds in each module's hand-authored {@code additional-spring-configuration-metadata.json}) into a
 * single {@code docs/reference/properties.md} table, grouped by capability. Reads the reactor tree
 * from the filesystem, so a full {@code mvn verify} (or a prior build) must have populated the
 * sibling {@code target/classes} directories.
 */
final class PropertiesReferenceGenerator {

    private static final ObjectMapper MAPPER = new ObjectMapper();

    private PropertiesReferenceGenerator() {
    }

    record Prop(String name, String type, String defaultValue, String description, String deprecation) {
    }

    /** Scans the reactor for {@code dc.platform.*} property metadata, de-duplicated and sorted by key. */
    static List<Prop> scan() {
        Path root = PlatformDocs.repoRoot();
        Map<String, Prop> byName = new TreeMap<>();
        try (Stream<Path> tree = Files.walk(root)) {
            tree.filter(p -> p.endsWith(Path.of("target", "classes", "META-INF", "spring-configuration-metadata.json")))
                    .filter(p -> !p.toString().replace('\\', '/').contains("/docs/platform-docs/"))
                    .forEach(metadata -> readProperties(metadata, byName));
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
        return new ArrayList<>(byName.values());
    }

    private static void readProperties(Path metadata, Map<String, Prop> byName) {
        try {
            JsonNode props = MAPPER.readTree(metadata.toFile()).path("properties");
            for (JsonNode p : props) {
                String name = p.path("name").asText("");
                if (!name.startsWith("dc.platform.")) {
                    continue;
                }
                byName.putIfAbsent(name, new Prop(
                        name,
                        simpleType(p.path("type").asText("")),
                        p.hasNonNull("defaultValue") ? p.get("defaultValue").asText() : "",
                        p.path("description").asText(""),
                        deprecation(p.path("deprecation"))));
            }
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    private static String deprecation(JsonNode node) {
        if (node.isMissingNode() || node.isNull()) {
            return "";
        }
        String replacement = node.path("replacement").asText("");
        String reason = node.path("reason").asText("");
        String level = node.path("level").asText("");
        StringBuilder sb = new StringBuilder(level.isEmpty() ? "deprecated" : level);
        if (!replacement.isEmpty()) {
            sb.append(" → ").append(replacement);
        }
        if (!reason.isEmpty()) {
            sb.append(" (").append(reason).append(')');
        }
        return sb.toString();
    }

    private static String simpleType(String type) {
        return type.replace("java.lang.", "")
                .replace("java.util.", "")
                .replace("java.time.", "");
    }

    /** Regenerates {@code docs/reference/properties.md}; returns the written path. */
    static Path generate() {
        List<Prop> props = scan();
        Map<String, List<Prop>> byCapability = new LinkedHashMap<>();
        props.stream()
                .sorted(Comparator.comparing(Prop::name))
                .forEach(p -> byCapability
                        .computeIfAbsent(PlatformDocs.capabilityOfKey(p.name()), k -> new ArrayList<>())
                        .add(p));

        StringBuilder md = new StringBuilder();
        md.append("# Configuration properties\n\n");
        md.append("> Generated by `PropertiesReferenceGenerator` from every module's ");
        md.append("`spring-configuration-metadata.json` at build time. Do not edit by hand.\n\n");
        md.append("Every platform property lives under the `dc.platform.<capability>` prefix, has a ");
        md.append("default in code, and is overridable in `application.yml`. Each capability's kill ");
        md.append("switch is `dc.platform.<capability>.enabled` (default `true`).\n");

        byCapability.forEach((capability, capProps) -> {
            md.append("\n## dc.platform.").append(capability).append("\n\n");
            md.append("| Key | Type | Default | Description | Deprecation |\n");
            md.append("|-----|------|---------|-------------|-------------|\n");
            for (Prop p : capProps) {
                md.append("| `").append(p.name()).append("` | ")
                        .append(cell(p.type())).append(" | ")
                        .append(p.defaultValue().isEmpty() ? "" : "`" + cell(p.defaultValue()) + "`").append(" | ")
                        .append(cell(p.description())).append(" | ")
                        .append(cell(p.deprecation())).append(" |\n");
            }
        });

        Path out = PlatformDocs.docsRoot().resolve("reference/properties.md");
        PlatformDocs.writeString(out, md.toString());
        return out;
    }

    private static final Pattern JAVADOC_INLINE_TAG =
            Pattern.compile("\\{@\\w+\\s+([^}]+)}");

    /** Markdown-table-safe cell: javadoc inline tags flattened, no raw pipes or newlines. */
    private static String cell(String raw) {
        // {@link a.b.Type#member} / {@code x} → the last readable segment; the metadata descriptions
        // are copied verbatim from record-component javadoc, so these tags leak through otherwise.
        String flattened = JAVADOC_INLINE_TAG.matcher(raw).replaceAll(m -> {
            String body = m.group(1).trim();
            int space = body.indexOf(' ');
            String ref = space < 0 ? body : body.substring(0, space);
            int lastDot = ref.lastIndexOf('.');
            return Matcher.quoteReplacement(lastDot < 0 ? ref : ref.substring(lastDot + 1));
        });
        return flattened.replace("\r", " ").replace("\n", " ").replace("|", "\\|").trim();
    }
}
