#set( $featureSet = ",${features}," )
#if($featureSet.contains(",data,"))
-- Feature sample (features=data): schema for the Note entity. Flyway owns the schema (Hibernate DDL is
-- off once Flyway runs); add V2__..., V3__... for every change instead of editing this file.
create table note (
    id   bigint generated by default as identity primary key,
    text varchar(255) not null
);
#end
