-- Schema for Order. Flyway owns it: platform-starter-data-jpa runs migrations from classpath:db/migration
-- at startup (and Hibernate DDL is off once Flyway is present), on H2 locally and PostgreSQL under -Ppg.
create table orders (
    id       bigint generated by default as identity primary key,
    customer varchar(255),
    amount   numeric(38, 2),
    status   varchar(32)
);
